/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author GUTO
 */
public class frmAvaliacaoDoTreinamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmSupervisor
     */
    public frmAvaliacaoDoTreinamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatotimo = new javax.swing.JCheckBox();
        chatregular = new javax.swing.JCheckBox();
        chatbom = new javax.swing.JCheckBox();
        chinstatotimo = new javax.swing.JCheckBox();
        chinstatregular = new javax.swing.JCheckBox();
        chinstatbom = new javax.swing.JCheckBox();
        chapindsim = new javax.swing.JCheckBox();
        chapindnao = new javax.swing.JCheckBox();
        nomeAt = new javax.swing.JTextField();
        codAt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pesqat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableat = new javax.swing.JTable();
        btncadap = new javax.swing.JButton();
        btneditat = new javax.swing.JButton();
        btndeletat = new javax.swing.JButton();
        btnlimpat = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        comentMap = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comentinst = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chatotimo.setText("ÓTIMO");
        getContentPane().add(chatotimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 99, 20));

        chatregular.setText("REGULAR");
        getContentPane().add(chatregular, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 99, 20));

        chatbom.setText("BOM");
        getContentPane().add(chatbom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 99, 20));

        chinstatotimo.setText("ÓTIMO");
        getContentPane().add(chinstatotimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 99, 20));

        chinstatregular.setText("REGULAR");
        getContentPane().add(chinstatregular, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 99, 20));

        chinstatbom.setText("BOM");
        getContentPane().add(chinstatbom, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 99, 20));

        chapindsim.setText("SIM");
        getContentPane().add(chapindsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 80, -1));

        chapindnao.setText("NÃO");
        getContentPane().add(chapindnao, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 100, 20));
        getContentPane().add(nomeAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 180, 20));

        codAt.setEnabled(false);
        getContentPane().add(codAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 30, 20));

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("AVALIAÇÃO DO TREINAMENTO ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" CODIGO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(" NOME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("MATERIAL APLICADO :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("INSTRUTOR:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/zoom.png"))); // NOI18N
        jLabel11.setText(" PESQUISAR :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));
        getContentPane().add(pesqat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 330, 20));

        tableat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 740, 90));

        btncadap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/accept.png"))); // NOI18N
        btncadap.setText("CADASTRAR");
        getContentPane().add(btncadap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 120, 30));

        btneditat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/user_edit.png"))); // NOI18N
        btneditat.setText("EDITAR");
        getContentPane().add(btneditat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 120, 30));

        btndeletat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/user_delete.png"))); // NOI18N
        btndeletat.setText("DELETAR");
        getContentPane().add(btndeletat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 120, 30));

        btnlimpat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/cancel.png"))); // NOI18N
        btnlimpat.setText("LIMPAR");
        getContentPane().add(btnlimpat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("COMENTÁRIO:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        getContentPane().add(comentMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 240, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("COMENTÁRIO:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));
        getContentPane().add(comentinst, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 240, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("VOCÊ INDICARIA ALGUÉM O TREINAMENTO ?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("NA SUA OPINIÃO , O QUE DEVERIA SER INCLUÍDO NO CURSO ?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 200, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadap;
    private javax.swing.JButton btndeletat;
    private javax.swing.JButton btneditat;
    private javax.swing.JButton btnlimpat;
    private javax.swing.JCheckBox chapindnao;
    private javax.swing.JCheckBox chapindsim;
    private javax.swing.JCheckBox chatbom;
    private javax.swing.JCheckBox chatotimo;
    private javax.swing.JCheckBox chatregular;
    private javax.swing.JCheckBox chinstatbom;
    private javax.swing.JCheckBox chinstatotimo;
    private javax.swing.JCheckBox chinstatregular;
    private javax.swing.JTextField codAt;
    private javax.swing.JTextField comentMap;
    private javax.swing.JTextField comentinst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField nomeAt;
    private javax.swing.JTextField pesqat;
    private javax.swing.JTable tableat;
    // End of variables declaration//GEN-END:variables
}
