
package Visual;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.awt.Frame.MAXIMIZED_BOTH;
import static java.awt.GridBagConstraints.BOTH;
import java.awt.PopupMenu;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

    public class frmRedeSocia extends javax.swing.JInternalFrame {
    
    
    
    public void frmFacebook() throws URISyntaxException{
        Desktop d =Desktop.getDesktop();
        try {
            d.browse(new URI("https://www.facebook.com/"));
        } catch (IOException ex) {
            Logger.getLogger(frmRedeSocial.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    } 
    public void frmInstagram() throws URISyntaxException{
        Desktop d =Desktop.getDesktop();
        try {
            d.browse(new URI("https://www.instagram.com/?hl=pt-br"));
        } catch (IOException ex) {
            Logger.getLogger(frmRedeSocial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void frmTwitter() throws URISyntaxException{
        Desktop d =Desktop.getDesktop();
        try {
            d.browse(new URI("https://www.twitter.com/login?lang=pt"));
        } catch (IOException ex) {
            Logger.getLogger(frmRedeSocial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void frmWhatsApp() throws URISyntaxException{
        Desktop d =Desktop.getDesktop();
        try {
            d.browse(new URI("https://www.whatsapp.com"));
        } catch (IOException ex) {
            Logger.getLogger(frmRedeSocial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void frmCultoAoVivo() throws URISyntaxException{
        Desktop d =Desktop.getDesktop();
        try {
            d.browse(new URI("https://www.youtube.com/c/getsemaniaovivo/live"));
        } catch (IOException ex) {
            Logger.getLogger(frmRedeSocial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void frmInforGet() throws URISyntaxException{
        Desktop d =Desktop.getDesktop();
        try {
            d.browse(new URI("https://getsemani.com.br/novosite/reunioes.php"));
        } catch (IOException ex) {
            Logger.getLogger(frmRedeSocial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }


    /**
     * Creates new form frmRedeSocia
     */
    public frmRedeSocia() {
        initComponents();
       this.setLocation(200,80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagem/Mãos Erguidas.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setName("Rede Social Voluntários"); // NOI18N

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/group.png"))); // NOI18N
        jLabel1.setText("Acesso A Redes Sociais : ");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 33));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Twiter.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 160, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/images.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 290, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Instagram.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, 150, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/facebook.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 90, 150, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Whatsapp.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 150, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/newspaper.png"))); // NOI18N
        jButton6.setText("Inforget");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1302, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            frmTwitter();
        } catch (URISyntaxException ex) {
            Logger.getLogger(frmRedeSocia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            frmWhatsApp();
        } catch (URISyntaxException ex) {
            Logger.getLogger(frmRedeSocia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            frmInforGet();
        } catch (URISyntaxException ex) {
            Logger.getLogger(frmRedeSocia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            frmCultoAoVivo();
        } catch (URISyntaxException ex) {
            Logger.getLogger(frmRedeSocia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            frmFacebook();
        } catch (URISyntaxException ex) {
            Logger.getLogger(frmRedeSocia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            frmInstagram();
        } catch (URISyntaxException ex) {
            Logger.getLogger(frmRedeSocia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
